apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
    env: dev
    tier: backend
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-deployment
    spec:
      containers:
      - image: busybox
        name: application
        command: ["sh", "-c", "sleep 1000"]
        resources: {}
status: {}