apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-deployment
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
        env: dev
        tier: frontend
    spec:
      containers:
      - image: nginx
        name: web
        resources: {}
status: {}