apiVersion: v1
kind: Pod
metadata:
  name: host-dir-mount
  labels:
    env: dev
    tier: frontend
spec:
  containers:
    - name:
      image: nginx
      command:
        - "sleep"
        - "4800"
      volumeMounts:
        - name: host-vol
          mountPath: /data
  volumes: 
    - name: host-vol
      hostPath:
        path: /data
        type: DirectoryOrCreate
