apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-1
  labels:
    env: prod
    tier: frontend
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-1
  labels:
    env: prod
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: my-pv-pod-1
  labels:
    env: prod
    tier: frontend
spec:
  containers:
    - name: red
      image: busybox
      command: ["sh", "-c", "sleep 4800"]
      volumeMounts:
        - name: mydata
          mountPath: /mydata
  volumes: 
    - name: mydata
      persistentVolumeClaim: 
        claimName: my-pvc-1
